switchTechChal/payments/urls.py
from django.urls import path
from . import views

app_name = 'payments'
urlpatterns = [
    # /payments/
    path('', views.listAll, name='allPayments'),
    path('payment/<payment_id>/', views.showPayment, name='showPayment'),
    path('newPayment/', views.newPayment, name='newPayment'),
    path('processPayment/', views.processPayment, name='processPayment'),
    path('deletePayment/<payment_id>/', views.deletePayment, name='deletePayment'),
    path('settlePayment/<payment_id>/', views.settlePayment, name='settlePayment'),
    path('search/', views.filterView, name='searchPayments'),

]

switchTechChal/payments/models.py
from django import forms
from django.db import models
from django.forms import ModelForm
import uuid

from django.forms.widgets import HiddenInput, Widget

# Create your models here.

class Base(models.Model):
    CC = "credit_card"
    MBWay = "mbway"
    SUCCESS = "success"
    ERROR = "error"
    SETTLED = "settled"

    payment_id = models.UUIDField(max_length=200, primary_key=True, default=uuid.uuid4)     # primary key, auto generated UUID
    amount = models.FloatField()                
    payment_method = models.CharField(max_length=50, default=CC, choices=[(CC, 'credit_card'), (MBWay, 'mbway')])
    created_at = models.DateTimeField(auto_now_add=True)          
    status = models.CharField(max_length=20, choices=[(SUCCESS, 'success'), (ERROR, 'error'), (SETTLED, 'settled')])
    settled_at = models.DateTimeField(null=True, blank=True)             
    settled_amount = models.FloatField(null=True, blank=True, default=0)
    def __str__(self):
        baseStr = "Payment ID: " + str(self.payment_id) + ", Amount: " + str(self.amount) + "€, Method: " + self.payment_method + ", Created at: " + str(self.created_at) + ", Status: " + self.status 
        if self.settled_at != None:
            return baseStr + ", Settled at: " + str(self.settled_at) + ", Settled amount: " + str(self.settled_amount) + "€"
        else:
            return baseStr

class CreditCard(models.Model):
    payment_id = models.ForeignKey(Base, on_delete=models.CASCADE)  # Foreign key to Base
    number = models.CharField(max_length=16)                                     
    name = models.CharField(max_length=30)                             
    expiration_month = models.CharField(max_length=2)   
    expiration_year = models.CharField(max_length=4)  
    cvv = models.CharField(max_length=3)
    def __str__(self):
        return str(self.payment_id) + ", Card Number: " + self.number + ", Name: " + self.name + ", Exp. Month: " + self.expiration_month + ", Exp. Year: " + self.expiration_year + ", CVV: " + self.cvv + "\n"
        
class MbWay(models.Model):
    payment_id = models.ForeignKey(Base, on_delete=models.CASCADE)  # Foreign key to base
    phone_number = models.CharField(max_length=9)
    def __str__(self):
        return str(self.payment_id) + ", Phone Number: " + self.phone_number + "\n"

class BaseForm(ModelForm):
    class Meta:
        model = Base
        fields = ('payment_id', 'amount', 'payment_method', 'status', 'settled_at', 'settled_amount')
        widgets = {
            'payment_id': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control', 'min': 0}),
            'payment_method': forms.Select(attrs={'class': 'form-control'}, choices=(Base.CC, Base.MBWay)),
            'settled_at': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'date'}),
            'settled_amount': forms.NumberInput(attrs={'class': 'form-control', 'min': 0, 'default': 0}),
            'status': forms.HiddenInput(attrs={'class': 'form-control', 'default':Base.ERROR}),
        }

class CreditCardForm(ModelForm):
    class Meta:
        model = CreditCard
        fields = '__all__'
        widgets = {
            'payment_id': forms.TextInput(attrs={'readonly': 'readonly'}),
            'number': forms.NumberInput(attrs={'class': 'form-control', 'min': 1111111111111111, 'placeholder': 1111111111111111}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'John Doe'}),
            'expiration_month': forms.NumberInput(attrs={'class': 'form-control', 'max': 12, 'min': 1}),
            'expiration_year': forms.NumberInput(attrs={'class': 'form-control', 'min': 2021}),
            'cvv': forms.NumberInput(attrs={'class': 'form-control', 'max': 999}),
        }

class MbWayForm(ModelForm):
    class Meta:
        model = MbWay
        fields = '__all__'
        widgets = {
            'payment_id': forms.TextInput(attrs={'readonly': 'readonly'}),
            'phone_number': forms.NumberInput(attrs={'class': 'form-control', 'maxlength': 9, 'placeholder': 910000000})
        }

switchTechChal/payments/forms.py
from django import forms
from django.forms import widgets

class SettleForm(forms.Form):
    def __init__(self, *args, **kwargs):
        pay_id = kwargs.pop('payment_id')
        amt = kwargs.pop('amount')
        sttl_at = kwargs.pop('settle_date')
        sttl_amt = kwargs.pop('settled_amount')
        super(SettleForm, self).__init__(*args, **kwargs)        
        self.fields['payment_id'] = forms.CharField(widget=widgets.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}), initial=pay_id, disabled=True)
        self.fields['amount'] = forms.FloatField(widget=widgets.NumberInput(attrs={'readonly': 'readonly', 'class': 'form-control'}), disabled=True, initial=amt)                
        self.fields['settled_at'] = forms.DateTimeField(widget=widgets.TextInput(attrs={'class': 'form-control', 'type': 'date'}),required=False, initial=sttl_at) 
        self.fields['settled_amount'] = forms.FloatField(widget=widgets.NumberInput(attrs={'class': 'form-control'}),required=False, max_value=amt, min_value=sttl_amt, initial=sttl_amt)

class FilterForm(forms.Form):
    filter_choices = (
        ('payment_id', 'PAYMENT_ID'),
        ('amount', 'AMOUNT'),
        ('payment_method', 'PAYMENT_METHOD'),
        ('status', 'STATUS'),
        ('created_at', 'CREATED_AT'),
        ('settled_at', 'SETTLED_AT'),
    )
    search = forms.CharField(required=False)
    filter_field = forms.ChoiceField(choices=filter_choices)

switchTechChal/payments/views.py
from django import forms
from django.db.models import base
from django.db.models.base import Model
from django.http.response import Http404, HttpResponsePermanentRedirect, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.template import loader

from .models import Base, CreditCard, MbWay, BaseForm, CreditCardForm, MbWayForm
from .forms import FilterForm, SettleForm

# Create your views here.
def listAll(request):
    allPayments = Base.objects.all()
    return render(request, 'payments/allPayments.html', {'allPayments': allPayments})

def showPayment(request, payment_id):
    payment = get_object_or_404(Base, payment_id=payment_id)    
    # credit_card
    if payment.payment_method == Base.CC:   
        full_payment = CreditCard.objects.get(payment_id=payment_id)
    # MBWay
    else:                                   
        full_payment = MbWay.objects.get(payment_id=payment_id)
    return render(request, 'payments/showPayment.html', {'payment_id': payment_id, 'payment': full_payment, 'notSettled': payment.amount!=payment.settled_amount})

def is_valid_queryparam(param):
    return param != '' and param is not None

def filter(request):
    payments = Base.objects.all()
    payment_id = request.GET.get('payment_id')
    min_amount = request.GET.get('min_amount')
    max_amount = request.GET.get('max_amount')
    payment_method = request.GET.get('payment_method')
    status = request.GET.get('status')
    min_created_at = request.GET.get('min_created_at')
    max_created_at = request.GET.get('max_created_at')
    min_settled_at = request.GET.get('min_settled_at')
    max_settled_at = request.GET.get('max_settled_at')

    if is_valid_queryparam(payment_id) and payment_id != "Choose...":
        payments = payments.filter(payment_id=payment_id)

    if is_valid_queryparam(min_amount):
        payments = payments.filter(amount__gte=min_amount)

    if is_valid_queryparam(max_amount):
        payments = payments.filter(amount__lte=max_amount)

    if is_valid_queryparam(payment_method) and payment_method != "Choose...":
        payments = payments.filter(payment_method=payment_method)

    if is_valid_queryparam(status) and status != "Choose...":
        payments = payments.filter(status=status)

    if is_valid_queryparam(min_created_at):
        payments = payments.filter(created_at__gte=min_created_at)

    if is_valid_queryparam(max_created_at):
        payments = payments.filter(created_at__lt=max_created_at)

    if is_valid_queryparam(min_settled_at):
        payments = payments.filter(settled_at__gte=min_settled_at)

    if is_valid_queryparam(max_settled_at):
        payments = payments.filter(settled_at__lt=max_settled_at)

    return payments

def filterView(request):
    return render(request, 'payments/filteredPayments.html', {'payments': filter(request), 'payment_ids': list(Base.objects.all().values_list('payment_id', flat=True)), 'status': (Base.SUCCESS, Base.SETTLED, Base.ERROR), 'pay_method': (Base.CC, Base.MBWay)})

def newPayment(request):
    form = BaseForm(request.POST or None)
    payment_id = form['payment_id'].value()
    if form.is_valid():
        form.save()
        request.session['payment_id'] = payment_id
        request.session['payment_method'] = form['payment_method'].value()
        return redirect('payments:processPayment')
    return render(request, 'payments/createPayment.html', {'form': form})

def processPayment(request):
    payment_method = request.session['payment_method']
    payment_id = request.session['payment_id']
    basePayment = get_object_or_404(Base, payment_id=payment_id)
    if payment_method == Base.CC:
        form = CreditCardForm(request.POST or None, initial={'payment_id': payment_id})
    else:
        form = MbWayForm(request.POST or None, initial={'payment_id': payment_id})
    if form.is_valid():
        form.save()
        if float(basePayment.amount) == float(basePayment.settled_amount):
            basePayment.status = Base.SETTLED
        else:
            basePayment.status = Base.SUCCESS
        basePayment.save()
        return redirect('payments:allPayments')
    return render(request, 'payments/processPayment.html', {'form': form, 'payment_method': payment_method})

def settlePayment(request, payment_id):
    payment = get_object_or_404(Base, payment_id=payment_id)
    amount = payment.amount
    settled_amount = payment.settled_amount
    last_settle = payment.settled_at
    if amount > settled_amount:
        form = SettleForm(request.POST or None, payment_id=payment_id, amount=amount, settle_date=last_settle, settled_amount=settled_amount)
        if form.is_valid():
            amt = float(form['settled_amount'].value())
            payment.settled_amount = amt
            payment.settled_at = form['settled_at'].value()
            if amt == amount:
                payment.status = Base.SETTLED
            payment.save()
            return redirect('payments:showPayment', payment_id)
    return render(request, 'payments/settlePayment.html', {'payment_id': payment_id, 'form': form})

def deletePayment(request, payment_id):
    get_object_or_404(Base, payment_id=payment_id).delete()
    return redirect('payments:allPayments')

switchTechChal/payments/templates/payments/filteredPayments.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Filter Payments</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    <main role="main" class="container">
      <h3>Filter Payments</h3>
      <hr />
      <form method="GET" action=".">
        <div class="form-row">
            <div class="form-group col-12">
                <label for="payment_id">Payment ID</label>
                <select id="payment_id" class="form-control" name="payment_id">
                <option selected>Choose...</option>
                {% for p in payment_ids %}
                <option value="{{ p }}">{{ p }}</option>
                {% endfor %}
                </select>
            </div>        
        </div>
        <div class="form-row">
            <div class="form-group col-md-4 col-lg-3">
                <label for="status">Status</label>
                <select id="status" class="form-control" name="status">
                <option selected>Choose...</option>
                {% for st in status %}
                <option value="{{ st }}">{{ st }}</option>
                {% endfor %}
                </select>
            </div>
            <div class="form-group col-md-4 col-lg-3">
                <label for="payment_method">Payment Method</label>
                <select id="payment_method" class="form-control" name="payment_method">
                <option selected>Choose...</option>
                {% for p in pay_method %}
                <option value="{{ p }}">{{ p }}</option>
                {% endfor %}
                </select>
            </div>
            <div class="form-group col-md-4 col-lg-3">
                <label for="min_amount">Minimum Amount</label>
                <input type="number" min=0 class="form-control" id="min_amount" placeholder="0" name="min_amount">
            </div>
            <div class="form-group col-md-4 col-lg-3">
                <label for="max_amount">Maximum Amount</label>
                <input type="number" min=0 class="form-control" id="max_amount" placeholder="10000?" name="max_amount">
            </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-2 col-lg-3">
            <label for="min_created_at">Minimum creation date</label>
            <input type="date" class="form-control" id="min_created_at" name="min_created_at">
          </div>
          <div class="form-group col-md-2 col-lg-3">
            <label for="max_created_at">Maximum creation date</label>
            <input type="date" class="form-control" id="max_created_at" name="max_created_at">
          </div>
          <div class="form-group col-md-2 col-lg-3">
            <label for="min_settled_at">Minimum settle date</label>
            <input type="date" class="form-control" id="min_settled_at" name="min_settled_at">
          </div>
          <div class="form-group col-md-2 col-lg-3">
            <label for="max_settled_at">Maximum settle date</label>
            <input type="date" class="form-control" id="max_settled_at" name="max_settled_at">
          </div>
        </div>
        <a href="{% url 'payments:allPayments' %}"><button type="button" class="btn btn-primary" onclick="">Back</button></a>
        <a href="{% url 'payments:searchPayments' %}"><button style="float: right; margin-left: 1%;" type="button" class="btn btn-warning">Clear Filters</button></a>
        <button style="float: right;" type="submit" class="btn btn-success">Search</button>
    </form>
      <hr />

      <div class="row">
        <ul>
          {% for payment in payments %}
            <li>
                <a href="{% url 'payments:showPayment' payment.payment_id %}">{{ payment }}</a>
            </li>
            <hr />
          {% endfor %}
        </ul>
      </div>

    </main>

</body>

</html>

switchTechChal/payments/templates/payments/showPayment.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Payment {{ payment_id }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    
    <main role="main" class="container">
        <h3>Payment {{ payment_id }}</h3>
        <hr />

        <ul>
            <li>{{ payment }}</li>
        </ul>
        
        <hr />
        <a href="{% url 'payments:deletePayment' payment_id %}"><button class="btn btn-danger" type="button" >Delete Payment</button></a>
        <a href="{% url 'payments:allPayments' %}"><button class="btn btn-primary" style="float: right;" type="button" >All Payments</button></a>
        <a href="{% url 'payments:searchPayments' %}"><button class="btn btn-primary" style="float: right; margin-right: 4px;" type="button" >Filter Payments</button></a>

        {% if notSettled %}
            <a href="{% url 'payments:settlePayment' payment_id %}"><button class="btn btn-success" type="button" >Settle Payment</button></a>
        {% endif %}
  
    </main>
  </body>